services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: k616kYMJSa1lNMp8pOSGtqcNU
    ports:
      - 27017:27017

  mongodb-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: k616kYMJSa1lNMp8pOSGtqcNU
      ME_CONFIG_MONGODB_URL: mongodb://root:k616kYMJSa1lNMp8pOSGtqcNU@mongo:27017/

  redis:
    image: redis/redis-stack:latest
    ports:
      - 6379:6379
