version: '3.5'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: k616kYMJSa1lNMp8pOSGtqcNU
    ports:
      - 27017:27017

  mongodb-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: k616kYMJSa1lNMp8pOSGtqcNU
      ME_CONFIG_MONGODB_URL: mongodb://root:k616kYMJSa1lNMp8pOSGtqcNU@mongo:27017/

  redis:
    image: redis/redis-stack:latest
    ports:
      - 6379:6379

  server:
    build:
      context: ./circles-backend
      dockerfile: dev.Dockerfile
    container_name: nest-server
    ports:
      - 4000:4000
    depends_on:
      - mongo
      - redis
    environment:
      MONGODB_URL: mongodb://root:k616kYMJSa1lNMp8pOSGtqcNU@mongo:27017/circles?authSource=admin
      REDIS_URL: redis://redis:6379
    volumes:
      - ./circles-backend/src:/server/src

  client:
    build:
      context: ./circles-frontend
      dockerfile: dev.Dockerfile
    container_name: client
    ports:
      - 3000:3000
    depends_on:
      - server
    restart: always
    environment:
      SERVER_BACKEND_URL: http://server:4000
      CLIENT_BACKEND_URL: http://localhost:4000
    volumes:
      - ./circles-frontend/src:/client/src
      - ./circles-frontend/public/:/client/public

